version: "3.7"

services:
  web:
    image: jordanst/cpucontrol:1.0.14
    restart: on-failure
    network_mode: "host"
    volumes:
      - /sys:/sys
      - ${APP_DATA_DIR}/data:/usr/src/app/data
    privileged: true
    environment:
      - PORT=3000
      - DATA_DIR=/usr/src/app/data
